
# apiVersion: v1
# kind: Pod
# metadata:
#   name: webapp-release-0-5
#   labels:
#     app: webapp
#     release: "0-5"
# spec:
#   containers:
#   - name: webapp
#     image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: webapp-release-0
#   labels:
#     app: webapp
#     release: "0"
# spec:
#   containers:
#   - name: webapp
#     image: richardchesterwood/k8s-fleetman-webapp-angular:release0
#      resources:
#         limits:
#           memory: 512Mi
#           cpu: "1"
#         requests:
#           memory: 256Mi
#           cpu: "0.2"
# ---
apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    app: queue
spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1
    resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"